os: windows
language: rust
rust:
  - stable

script:
  - cargo build
  - cargo install --force
  
deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    file: ./target/release/travis-windows-app.exe
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
  
